# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='nonce_str',
            field=models.CharField(default='5211929143', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='spbill_create_ip',
            field=models.CharField(default='192.168.1.106', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
