# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatpay', '0002_auto_20180616_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='nonce_str',
            field=models.CharField(default='1474908013', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='spbill_create_ip',
            field=models.CharField(default='10.106.148.245', max_length=20),
        ),
    ]
