# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatpay', '0002_auto_20180620_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='nonce_str',
            field=models.CharField(default='1359377647', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='spbill_create_ip',
            field=models.CharField(default='172.19.8.69', max_length=20),
        ),
    ]
