# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatpay', '0003_auto_20180619_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='nonce_str',
            field=models.CharField(default='2946435378', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='spbill_create_ip',
            field=models.CharField(default='10.106.148.152', max_length=20),
        ),
    ]
