# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('barcode', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('brand', models.CharField(blank=True, max_length=10)),
                ('originPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('scale', models.CharField(blank=True, max_length=10)),
                ('factory', models.CharField(blank=True, max_length=30)),
                ('priceChecker', models.CharField(blank=True, max_length=10)),
                ('supervisionCode', models.CharField(blank=True, max_length=30)),
                ('supervisor', models.CharField(blank=True, max_length=20)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('supervisorTel', models.CharField(blank=True, max_length=13)),
                ('promotionPrice', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=8), max_digits=8)),
                ('clubPrice', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=8), max_digits=8)),
                ('producePlace', models.CharField(blank=True, max_length=10)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
    ]
