# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='barcode',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
