# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandises', '0002_auto_20180529_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='brand',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
