# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandises', '0003_auto_20180531_0229'),
        ('merchandises', '0003_auto_20180606_1351'),
    ]

    operations = [
    ]
