# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_auto_20180529_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('paymentSN', models.CharField(blank=True, max_length=128)),
                ('tradeNo', models.CharField(blank=True, max_length=128)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('amountPay', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('amountAdd', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
            ],
        ),
    ]
