# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpGift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level1topup', models.IntegerField(default=50)),
                ('level1gift', models.IntegerField(default=3)),
                ('level2topup', models.IntegerField(default=100)),
                ('level2gift', models.IntegerField(default=8)),
                ('level3topup', models.IntegerField(default=200)),
                ('level3gift', models.IntegerField(default=20)),
                ('level4topup', models.IntegerField(default=500)),
                ('level4gift', models.IntegerField(default=60)),
                ('level5topup', models.IntegerField(default=1000)),
                ('level5gift', models.IntegerField(default=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
