# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topups', '0002_topupgift'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupgift',
            name='level0gift',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topupgift',
            name='level0topup',
            field=models.IntegerField(default=20),
        ),
    ]
