# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('telephone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=50)),
                ('isDefault', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ESL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('labelID', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baidu_appid', models.CharField(max_length=128)),
                ('baidu_group_id', models.CharField(max_length=128)),
                ('baidu_uid', models.CharField(max_length=128)),
                ('baidu_faceid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('barcode', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('brand', models.CharField(blank=True, max_length=10)),
                ('originPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('scale', models.CharField(blank=True, max_length=10)),
                ('factory', models.CharField(blank=True, max_length=30)),
                ('priceChecker', models.CharField(blank=True, max_length=10)),
                ('supervisionCode', models.CharField(blank=True, max_length=30)),
                ('supervisor', models.CharField(blank=True, max_length=20)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('supervisorTel', models.DecimalField(blank=True, decimal_places=0, max_digits=11)),
                ('promotionPrice', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=8), max_digits=8)),
                ('clubPrice', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=8), max_digits=8)),
                ('producePlace', models.CharField(blank=True, max_length=10)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=3)),
                ('paymentMethod', models.CharField(max_length=10)),
                ('paymentSN', models.CharField(max_length=30)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bill', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('payTime', models.DateTimeField(blank=True)),
                ('dispatchTime', models.DateTimeField(blank=True)),
                ('receivedTime', models.DateTimeField(blank=True)),
                ('cancelTime', models.DateTimeField(blank=True)),
                ('addressID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Address')),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchandiseNum', models.IntegerField(default=1)),
                ('merchandiseID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Merchandise')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.IntegerField(default=900)),
                ('width', models.IntegerField(default=320)),
                ('height', models.IntegerField(default=1600)),
                ('level', models.IntegerField(default=4)),
                ('capacity', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFIDtag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EPC', models.CharField(max_length=20)),
                ('TID', models.CharField(blank=True, max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('merchandiseID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clubPriceLevel1', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('clubPriceLevel2', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('clubPriceLevel3', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('clubPriceLevel4', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('merchandiseID', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Merchandise')),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('longitude', models.CharField(blank=True, max_length=10)),
                ('latitude', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(max_length=15)),
                ('locationDetail', models.CharField(blank=True, max_length=200)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacity', models.IntegerField(blank=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('openingTime', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('number', models.IntegerField(default=1)),
                ('arriveDate', models.DateField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('merchandiseID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Merchandise')),
                ('shopID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Shop')),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=30)),
                ('contactName', models.CharField(max_length=20)),
                ('contactPhone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('province', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('area', models.CharField(blank=True, max_length=15)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category')),
            ],
            options={
                'ordering': ('companyName',),
            },
        ),
        migrations.CreateModel(
            name='WUser',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openid', models.CharField(blank=True, max_length=30)),
                ('session_key', models.CharField(blank=True, max_length=30)),
                ('code', models.CharField(default=None, max_length=32)),
                ('nickName', models.CharField(max_length=32)),
                ('avatarUrl', models.URLField(blank=True)),
                ('gender', models.IntegerField(default=2)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('province', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=15)),
                ('language', models.CharField(blank=True, max_length=15)),
                ('level', models.IntegerField(default=1)),
                ('point', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('faceExisted', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='supplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Supplier'),
        ),
        migrations.AddField(
            model_name='saleevent',
            name='shopID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Shop'),
        ),
        migrations.AddField(
            model_name='rack',
            name='shopID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='shopID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.WUser'),
        ),
        migrations.AddField(
            model_name='face',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WUser'),
        ),
        migrations.AddField(
            model_name='esl',
            name='merchandiseID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Merchandise'),
        ),
        migrations.AddField(
            model_name='esl',
            name='rackID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Rack'),
        ),
        migrations.AddField(
            model_name='address',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WUser'),
        ),
    ]
