# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.IntegerField(default=900)),
                ('width', models.IntegerField(default=320)),
                ('height', models.IntegerField(default=1600)),
                ('level', models.IntegerField(default=4)),
                ('capacity', models.IntegerField(blank=True)),
                ('shopID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shops.Shop')),
            ],
        ),
    ]
