# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_auto_20180529_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('score', models.FloatField(default=0.0)),
                ('user_info', models.CharField(blank=True, max_length=100)),
                ('group_id', models.CharField(default='customers', max_length=20)),
                ('operation', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
            ],
        ),
    ]
