# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('longitude', models.CharField(blank=True, max_length=10)),
                ('latitude', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(max_length=15)),
                ('locationDetail', models.CharField(blank=True, max_length=200)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacity', models.IntegerField(blank=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('openingTime', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
    ]
