# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(blank=True, max_length=30)),
                ('session_key', models.CharField(blank=True, max_length=30)),
                ('code', models.CharField(default=None, max_length=32)),
                ('nickName', models.CharField(max_length=32)),
                ('avatarUrl', models.URLField(blank=True)),
                ('gender', models.IntegerField(default=2)),
                ('city', models.CharField(blank=True, max_length=15)),
                ('province', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=15)),
                ('language', models.CharField(blank=True, max_length=15)),
                ('level', models.IntegerField(default=1)),
                ('point', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('faceExisted', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
    ]
