# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
