# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchandises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('labelID', models.CharField(max_length=8)),
                ('merchandiseID', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='merchandises.Merchandise')),
            ],
        ),
    ]
