# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_no', models.CharField(blank=True, max_length=128)),
                ('out_trade_no', models.CharField(max_length=128)),
                ('buyer_logon_id', models.CharField(blank=True, max_length=128)),
                ('trade_status', models.CharField(blank=True, max_length=32)),
                ('total_amount', models.CharField(max_length=11)),
                ('invoice_amount', models.CharField(blank=True, max_length=11)),
                ('receipt_amount', models.CharField(blank=True, max_length=11)),
                ('store_id', models.CharField(blank=True, max_length=32)),
                ('buyer_user_id', models.CharField(blank=True, max_length=16)),
                ('operation', models.CharField(max_length=20)),
                ('qr_code', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
