# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('merchandises', '0001_initial'),
        ('customers', '0001_initial'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('paymentMethod', models.CharField(max_length=10)),
                ('paymentSN', models.CharField(blank=True, max_length=128)),
                ('tradeNo', models.CharField(blank=True, max_length=128)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('delivery', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('balanceUse', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payPrice', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('totalNum', models.IntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('payTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatchTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('receivedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('addressID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='addresses.Address')),
                ('shopID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shops.Shop')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
            ],
            options={
                'ordering': ('createTime',),
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchandiseNum', models.IntegerField(default=1)),
                ('priceOnSold', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('merchandiseID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchandises.Merchandise')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='orders.Order')),
            ],
        ),
    ]
